name: petween
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_sign_in: ^4.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^0.8.2


  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: true
  ios: true
  image_path_ios: "launcher/yellowfoot.jpg"
  image_path_android: "launcher/yellowfoot.jpg"

flutter:
  uses-material-design: true
  assets:
  - assets/catfoot.png